//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_GoToDie: Bright.Config.BeanBase
{
    public ActionCfg_GoToDie(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        IsOrgDeathShow = _buf.ReadBool();
        DeathShow = _buf.ReadString();
        PostInit();
    }

    public static ActionCfg_GoToDie DeserializeActionCfg_GoToDie(ByteBuf _buf)
    {
        return new ActionCfg_GoToDie(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 是否使用原来的死亡表现
    /// </summary>
    public bool IsOrgDeathShow { get; private set; }
    /// <summary>
    /// 死亡表现(不使用原来的，则会使用这个)
    /// </summary>
    public string DeathShow { get; private set; }
    public ActionCfg_DeathShow DeathShow_Ref { get; private set; }

    public const int __ID__ = -1168071988;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.DeathShow_Ref = (_tables["ActionCfg_DeathShowCategory"] as ActionCfg_DeathShowCategory).GetOrDefault(DeathShow);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "IsOrgDeathShow:" + IsOrgDeathShow + ","
        + "DeathShow:" + DeathShow + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}