//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 指定方向-扇形
/// </summary>
public sealed partial class ActionCallShow_Self_UmbellateArea:  ActionCallCasterShow 
{
    public ActionCallShow_Self_UmbellateArea(ByteBuf _buf)  : base(_buf) 
    {
        UmbellateArea = UmbellateArea.DeserializeUmbellateArea(_buf);
        PostInit();
    }

    public static ActionCallShow_Self_UmbellateArea DeserializeActionCallShow_Self_UmbellateArea(ByteBuf _buf)
    {
        return new ActionCallShow_Self_UmbellateArea(_buf);
    }

    /// <summary>
    /// 扇形信息
    /// </summary>
    public UmbellateArea UmbellateArea { get; private set; }

    public const int __ID__ = 435455647;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        UmbellateArea?.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        UmbellateArea?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "UmbellateArea:" + UmbellateArea + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}