//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_EffectCreate: Bright.Config.BeanBase
{
    public ActionCfg_EffectCreate(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ResId = _buf.ReadString();
        Key = _buf.ReadString();
        MaxKeyNum = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        IsSceneEffect = _buf.ReadBool();
        OffSetInfo = OffSetInfo.DeserializeOffSetInfo(_buf);
        PostInit();
    }

    public static ActionCfg_EffectCreate DeserializeActionCfg_EffectCreate(ByteBuf _buf)
    {
        return new ActionCfg_EffectCreate(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 资源id
    /// </summary>
    public string ResId { get; private set; }
    public ResEffectCfg ResId_Ref { get; private set; }
    /// <summary>
    /// 唯一key(用来便于准确删除)
    /// </summary>
    public string Key { get; private set; }
    /// <summary>
    /// 指定key后限制最大数量
    /// </summary>
    public int MaxKeyNum { get; private set; }
    /// <summary>
    /// 持续时间(s),-1表示永久
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// 是否场景特效
    /// </summary>
    public bool IsSceneEffect { get; private set; }
    public OffSetInfo OffSetInfo { get; private set; }

    public const int __ID__ = 1283151998;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.ResId_Ref = (_tables["ResEffectCfgCategory"] as ResEffectCfgCategory).GetOrDefault(ResId);
        OffSetInfo?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        OffSetInfo?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "ResId:" + ResId + ","
        + "Key:" + Key + ","
        + "MaxKeyNum:" + MaxKeyNum + ","
        + "Duration:" + Duration + ","
        + "IsSceneEffect:" + IsSceneEffect + ","
        + "OffSetInfo:" + OffSetInfo + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}