//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_CallAoe: Bright.Config.BeanBase
{
    public ActionCfg_CallAoe(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        AoeId = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BeCallActorActionId = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); BeCallActorActionId.Add(_e0);}}
        Duration = _buf.ReadFloat();
        AoeTargetCondition = AoeTargetCondition.DeserializeAoeTargetCondition(_buf);
        OffSetInfo = OffSetInfo.DeserializeOffSetInfo(_buf);
        MoveTweenId = _buf.ReadString();
        PostInit();
    }

    public static ActionCfg_CallAoe DeserializeActionCfg_CallAoe(ByteBuf _buf)
    {
        return new ActionCfg_CallAoe(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// AoeId
    /// </summary>
    public string AoeId { get; private set; }
    public AoeCfg AoeId_Ref { get; private set; }
    /// <summary>
    /// 被召唤时的Action事件
    /// </summary>
    public System.Collections.Generic.List<string> BeCallActorActionId { get; private set; }
    /// <summary>
    /// 持续时间(s)
    /// </summary>
    public float Duration { get; private set; }
    public AoeTargetCondition AoeTargetCondition { get; private set; }
    public OffSetInfo OffSetInfo { get; private set; }
    /// <summary>
    /// 飞行轨迹
    /// </summary>
    public string MoveTweenId { get; private set; }
    public MoveTweenCfg MoveTweenId_Ref { get; private set; }

    public const int __ID__ = -801855096;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.AoeId_Ref = (_tables["AoeCfgCategory"] as AoeCfgCategory).GetOrDefault(AoeId);
        AoeTargetCondition?.Resolve(_tables);
        OffSetInfo?.Resolve(_tables);
        this.MoveTweenId_Ref = (_tables["MoveTweenCfgCategory"] as MoveTweenCfgCategory).GetOrDefault(MoveTweenId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        AoeTargetCondition?.TranslateText(translator);
        OffSetInfo?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "AoeId:" + AoeId + ","
        + "BeCallActorActionId:" + Bright.Common.StringUtil.CollectionToString(BeCallActorActionId) + ","
        + "Duration:" + Duration + ","
        + "AoeTargetCondition:" + AoeTargetCondition + ","
        + "OffSetInfo:" + OffSetInfo + ","
        + "MoveTweenId:" + MoveTweenId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}