//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 投射点-附近单体
/// </summary>
public sealed partial class ActionCallShow_Camera_Unit:  ActionCallCasterShow 
{
    public ActionCallShow_Camera_Unit(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static ActionCallShow_Camera_Unit DeserializeActionCallShow_Camera_Unit(ByteBuf _buf)
    {
        return new ActionCallShow_Camera_Unit(_buf);
    }


    public const int __ID__ = -1606280688;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}