//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 远处-范围
/// </summary>
public sealed partial class ActionCallShow_Drag_OtherArea:  ActionCallShow_Drag 
{
    public ActionCallShow_Drag_OtherArea(ByteBuf _buf)  : base(_buf) 
    {
        RangeRadius = _buf.ReadFloat();
        PostInit();
    }

    public static ActionCallShow_Drag_OtherArea DeserializeActionCallShow_Drag_OtherArea(ByteBuf _buf)
    {
        return new ActionCallShow_Drag_OtherArea(_buf);
    }

    /// <summary>
    /// 效果半径
    /// </summary>
    public float RangeRadius { get; private set; }

    public const int __ID__ = -944281216;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "RangeRadius:" + RangeRadius + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}