//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 添加Buff
/// </summary>
public sealed partial class AddBuffInfo: Bright.Config.BeanBase
{
    public AddBuffInfo(ByteBuf _buf) 
    {
        Duration = _buf.ReadFloat();
        AddStack = _buf.ReadInt();
        BuffAction = BuffAction.DeserializeBuffAction(_buf);
        BuffId = _buf.ReadString();
        PostInit();
    }

    public static AddBuffInfo DeserializeAddBuffInfo(ByteBuf _buf)
    {
        return new AddBuffInfo(_buf);
    }

    /// <summary>
    /// 持续时间(s)
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// 新增的层数
    /// </summary>
    public int AddStack { get; private set; }
    /// <summary>
    /// buff基本逻辑
    /// </summary>
    public BuffAction BuffAction { get; private set; }
    /// <summary>
    /// buffId
    /// </summary>
    public string BuffId { get; private set; }

    public const int __ID__ = -829285566;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        BuffAction?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        BuffAction?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Duration:" + Duration + ","
        + "AddStack:" + AddStack + ","
        + "BuffAction:" + BuffAction + ","
        + "BuffId:" + BuffId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}