//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 移除包含tag的Buff
/// </summary>
public sealed partial class BuffRemoveByTag:  BuffRemoveType 
{
    public BuffRemoveByTag(ByteBuf _buf)  : base(_buf) 
    {
        BuffTagType = (BuffTagType)_buf.ReadInt();
        PostInit();
    }

    public static BuffRemoveByTag DeserializeBuffRemoveByTag(ByteBuf _buf)
    {
        return new BuffRemoveByTag(_buf);
    }

    public BuffTagType BuffTagType { get; private set; }

    public const int __ID__ = -834748628;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffTagType:" + BuffTagType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}