//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 匹配buffTagGroupType
/// </summary>
public sealed partial class ByBuffTagGroupType:  BuffDealSelectCondition 
{
    public ByBuffTagGroupType(ByteBuf _buf)  : base(_buf) 
    {
        BuffTagGroupType = (BuffTagGroupType)_buf.ReadInt();
        PostInit();
    }

    public static ByBuffTagGroupType DeserializeByBuffTagGroupType(ByteBuf _buf)
    {
        return new ByBuffTagGroupType(_buf);
    }

    public BuffTagGroupType BuffTagGroupType { get; private set; }

    public const int __ID__ = 1726492265;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffTagGroupType:" + BuffTagGroupType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}