//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 判断当前选中对象数量(目前仅AttackArea时判断是否攻击到人使用)
/// </summary>
public sealed partial class ChkSelectUnitNumCondition:  UnitConditionBase 
{
    public ChkSelectUnitNumCondition(ByteBuf _buf)  : base(_buf) 
    {
        Num = _buf.ReadInt();
        PostInit();
    }

    public static ChkSelectUnitNumCondition DeserializeChkSelectUnitNumCondition(ByteBuf _buf)
    {
        return new ChkSelectUnitNumCondition(_buf);
    }

    public int Num { get; private set; }

    public const int __ID__ = -458527461;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "Num:" + Num + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}