//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 检查塔拥有数量
/// </summary>
public sealed partial class ConditionStatusChkTowerNum:  ConditionStatusChkBase 
{
    public ConditionStatusChkTowerNum(ByteBuf _buf)  : base(_buf) 
    {
        TowerType = (TowerType)_buf.ReadInt();
        TowerCfgId = _buf.ReadString();
        NeedTowerCount = _buf.ReadInt();
        ConditionCompare = (ConditionCompare)_buf.ReadInt();
        PostInit();
    }

    public static ConditionStatusChkTowerNum DeserializeConditionStatusChkTowerNum(ByteBuf _buf)
    {
        return new ConditionStatusChkTowerNum(_buf);
    }

    public TowerType TowerType { get; private set; }
    public string TowerCfgId { get; private set; }
    public TowerDefense_TowerCfg TowerCfgId_Ref { get; private set; }
    public int NeedTowerCount { get; private set; }
    public ConditionCompare ConditionCompare { get; private set; }

    public const int __ID__ = -716531850;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        this.TowerCfgId_Ref = (_tables["TowerDefense_TowerCfgCategory"] as TowerDefense_TowerCfgCategory).GetOrDefault(TowerCfgId);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "TowerType:" + TowerType + ","
        + "TowerCfgId:" + TowerCfgId + ","
        + "NeedTowerCount:" + NeedTowerCount + ","
        + "ConditionCompare:" + ConditionCompare + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}