//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 伤害计算类型
    /// </summary>
    public enum DamageType
    {
        /// <summary>
        /// 固定血量
        /// </summary>
        FixedBlood = 1,
        /// <summary>
        /// 固定攻击者的总血量的百分比
        /// </summary>
        PercentTotalBloodAttacker = 2,
        /// <summary>
        /// 固定受击者的总血量的百分比
        /// </summary>
        PercentTotalBloodBeHurter = 3,
        /// <summary>
        /// 固定攻击者的当前血量的百分比
        /// </summary>
        PercentCurBloodAttacker = 4,
        /// <summary>
        /// 固定受击者的当前血量的百分比
        /// </summary>
        PercentCurBloodBeHurter = 5,
        /// <summary>
        /// 按照属性进行计算
        /// </summary>
        PropertyBlood = 6,
        /// <summary>
        /// 按照来源配置(技能)的方式来计算
        /// </summary>
        LastSelectBlood = 7,
    }

} 
