//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 特效表现节点类型
    /// </summary>
    public enum EffectNodeName
    {
        /// <summary>
        /// 以自身做偏移
        /// </summary>
        Self = 0,
        /// <summary>
        /// 以施加者做偏移(例如子弹击中大体型怪,这时候以子弹位置来表现)
        /// </summary>
        Caster = 1,
    }

} 
