//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 品质类型
    /// </summary>
    public enum QualityType
    {
        /// <summary>
        /// 普通
        /// </summary>
        Ordinary = 0,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 1,
        /// <summary>
        /// 史诗
        /// </summary>
        Epic = 2,
    }

} 
