//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 问卷表
/// </summary>
[Config]
public partial class QuestionnaireCfgCategory: ConfigSingleton<QuestionnaireCfgCategory>
{
    private readonly Dictionary<string, QuestionnaireCfg> _dataMap;
    private readonly List<QuestionnaireCfg> _dataList;
    
    public QuestionnaireCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, QuestionnaireCfg>();
        _dataList = new List<QuestionnaireCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            QuestionnaireCfg _v;
            _v = QuestionnaireCfg.DeserializeQuestionnaireCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, QuestionnaireCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<QuestionnaireCfg> DataList => _dataList;

    public QuestionnaireCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public QuestionnaireCfg Get(string key) => _dataMap[key];
    public QuestionnaireCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(QuestionnaireCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}