//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 存储string的key
    /// </summary>
    public enum RecordKeyString
    {
        RecordKeyString1 = 1,
        RecordKeyString2 = 2,
        RecordKeyString3 = 3,
        RecordKeyString4 = 4,
        RecordKeyString5 = 5,
    }

} 
