//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 判断当前是否类型的技能
/// </summary>
public sealed partial class SkillSlotTypeCondition:  UnitConditionBase 
{
    public SkillSlotTypeCondition(ByteBuf _buf)  : base(_buf) 
    {
        SkillSlotType = (SkillSlotType)_buf.ReadInt();
        SkillSlotIndex = _buf.ReadInt();
        PostInit();
    }

    public static SkillSlotTypeCondition DeserializeSkillSlotTypeCondition(ByteBuf _buf)
    {
        return new SkillSlotTypeCondition(_buf);
    }

    /// <summary>
    /// 技能类型
    /// </summary>
    public SkillSlotType SkillSlotType { get; private set; }
    /// <summary>
    /// 技能类型序号(-1表示所有,0表示第一个)
    /// </summary>
    public int SkillSlotIndex { get; private set; }

    public const int __ID__ = -496017550;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "SkillSlotType:" + SkillSlotType + ","
        + "SkillSlotIndex:" + SkillSlotIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}