//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 停在原地(可能在空中)
/// </summary>
public sealed partial class StayMoveTweenType:  MoveTweenType 
{
    public StayMoveTweenType(ByteBuf _buf)  : base(_buf) 
    {
        KeepHorizontal = _buf.ReadBool();
        PostInit();
    }

    public static StayMoveTweenType DeserializeStayMoveTweenType(ByteBuf _buf)
    {
        return new StayMoveTweenType(_buf);
    }

    /// <summary>
    /// 是否保持水平
    /// </summary>
    public bool KeepHorizontal { get; private set; }

    public const int __ID__ = -1032061573;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "KeepHorizontal:" + KeepHorizontal + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}