//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 目标减当前的高度差
/// </summary>
public sealed partial class TargetAltitudeDifferenceCondition:  UnitConditionBase 
{
    public TargetAltitudeDifferenceCondition(ByteBuf _buf)  : base(_buf) 
    {
        DisHeight = _buf.ReadFloat();
        PostInit();
    }

    public static TargetAltitudeDifferenceCondition DeserializeTargetAltitudeDifferenceCondition(ByteBuf _buf)
    {
        return new TargetAltitudeDifferenceCondition(_buf);
    }

    /// <summary>
    /// 高度差
    /// </summary>
    public float DisHeight { get; private set; }

    public const int __ID__ = -734865941;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "DisHeight:" + DisHeight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}