//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TimelineNode: Bright.Config.BeanBase
{
    public TimelineNode(ByteBuf _buf) 
    {
        TimeElapsed = _buf.ReadFloat();
        ActionId = _buf.ReadString();
        ActionCallParam = ActionCallParam.DeserializeActionCallParam(_buf);
        PostInit();
    }

    public static TimelineNode DeserializeTimelineNode(ByteBuf _buf)
    {
        return new TimelineNode(_buf);
    }

    /// <summary>
    /// Timeline运行多久之后发生，单位：秒
    /// </summary>
    public float TimeElapsed { get; private set; }
    /// <summary>
    /// 触发action
    /// </summary>
    public string ActionId { get; private set; }
    public ActionCallParam ActionCallParam { get; private set; }

    public const int __ID__ = 1630749187;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        ActionCallParam?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ActionCallParam?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "TimeElapsed:" + TimeElapsed + ","
        + "ActionId:" + ActionId + ","
        + "ActionCallParam:" + ActionCallParam + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}