//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TowerDefense_ChallengeLevelCfg: Bright.Config.BeanBase
{
    public TowerDefense_ChallengeLevelCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        BattleLevel = _buf.ReadString();
        FirstClearDropItem = _buf.ReadString();
        RepeatClearDropItem = _buf.ReadString();
        PostInit();
    }

    public static TowerDefense_ChallengeLevelCfg DeserializeTowerDefense_ChallengeLevelCfg(ByteBuf _buf)
    {
        return new TowerDefense_ChallengeLevelCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 关卡索引
    /// </summary>
    public string BattleLevel { get; private set; }
    public GamePlayBattleLevelCfg BattleLevel_Ref { get; private set; }
    /// <summary>
    /// 首通掉落（预留）
    /// </summary>
    public string FirstClearDropItem { get; private set; }
    /// <summary>
    /// 重复掉落（预留）
    /// </summary>
    public string RepeatClearDropItem { get; private set; }

    public const int __ID__ = 1113511035;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.BattleLevel_Ref = (_tables["GamePlayBattleLevelCfgCategory"] as GamePlayBattleLevelCfgCategory).GetOrDefault(BattleLevel);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "BattleLevel:" + BattleLevel + ","
        + "FirstClearDropItem:" + FirstClearDropItem + ","
        + "RepeatClearDropItem:" + RepeatClearDropItem + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}