//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TowerDefense_TowerCfg: Bright.Config.BeanBase
{
    public TowerDefense_TowerCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Type = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        UnitId = _buf.ReadString();
        Level = _buf.ReadInt();
        BuyTowerCostGold = _buf.ReadInt();
        NextTowerId = _buf.ReadString();
        NewTowerCostCount = _buf.ReadInt();
        AiCfgId = _buf.ReadString();
        PostInit();
    }

    public static TowerDefense_TowerCfg DeserializeTowerDefense_TowerCfg(ByteBuf _buf)
    {
        return new TowerDefense_TowerCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// unitId
    /// </summary>
    public string UnitId { get; private set; }
    public UnitCfg UnitId_Ref { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 购买消耗金币
    /// </summary>
    public int BuyTowerCostGold { get; private set; }
    /// <summary>
    /// 下一级id
    /// </summary>
    public string NextTowerId { get; private set; }
    public TowerDefense_TowerCfg NextTowerId_Ref { get; private set; }
    /// <summary>
    /// 升级消耗数量
    /// </summary>
    public int NewTowerCostCount { get; private set; }
    /// <summary>
    /// aiCfgId
    /// </summary>
    public string AiCfgId { get; private set; }

    public const int __ID__ = -1994510109;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.UnitId_Ref = (_tables["UnitCfgCategory"] as UnitCfgCategory).GetOrDefault(UnitId);
        this.NextTowerId_Ref = (_tables["TowerDefense_TowerCfgCategory"] as TowerDefense_TowerCfgCategory).GetOrDefault(NextTowerId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "UnitId:" + UnitId + ","
        + "Level:" + Level + ","
        + "BuyTowerCostGold:" + BuyTowerCostGold + ","
        + "NextTowerId:" + NextTowerId + ","
        + "NewTowerCostCount:" + NewTowerCostCount + ","
        + "AiCfgId:" + AiCfgId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}