//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TowerDefense_TowerCfg: Bright.Config.BeanBase
{
    public TowerDefense_TowerCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Type = (TowerType)_buf.ReadInt();
        QualityRank = (QualityRank)_buf.ReadInt();
        IsShowTutorialInBattle = _buf.ReadBool();
        MaxTiltedUpAngle = _buf.ReadFloat();
        MaxTiltedDownAngle = _buf.ReadFloat();
        TutorialCfgId = _buf.ReadString();
        IsShowInBattleDeckUI = _buf.ReadBool();
        UnLockCondition = UnLockConditionBase.DeserializeUnLockConditionBase(_buf);
        Tower2UnitInfo = TowerToUnitBase.DeserializeTowerToUnitBase(_buf);
        BuyTowerCostGold = _buf.ReadInt();
        ReclaimTowerCostGold = _buf.ReadInt();
        ScaleTowerCostGold = _buf.ReadInt();
        NextTowerId = _buf.ReadString();
        NewTowerCostCount = _buf.ReadInt();
        AiCfgId = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CreateActionIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); CreateActionIds.Add(_e0);}}
        PostInit();
    }

    public static TowerDefense_TowerCfg DeserializeTowerDefense_TowerCfg(ByteBuf _buf)
    {
        return new TowerDefense_TowerCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    public ItemCfg Id_Ref { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public TowerType Type { get; private set; }
    /// <summary>
    /// 品阶
    /// </summary>
    public QualityRank QualityRank { get; private set; }
    /// <summary>
    /// 是否需要在战斗中出现
    /// </summary>
    public bool IsShowTutorialInBattle { get; private set; }
    /// <summary>
    /// 最大上仰角度
    /// </summary>
    public float MaxTiltedUpAngle { get; private set; }
    /// <summary>
    /// 最大俯视角度
    /// </summary>
    public float MaxTiltedDownAngle { get; private set; }
    /// <summary>
    /// 指引视频
    /// </summary>
    public string TutorialCfgId { get; private set; }
    public TutorialCfg TutorialCfgId_Ref { get; private set; }
    /// <summary>
    /// 是否在出战UI面板中展示
    /// </summary>
    public bool IsShowInBattleDeckUI { get; private set; }
    /// <summary>
    /// 解锁条件
    /// </summary>
    public UnLockConditionBase UnLockCondition { get; private set; }
    public TowerToUnitBase Tower2UnitInfo { get; private set; }
    /// <summary>
    /// 购买消耗金币
    /// </summary>
    public int BuyTowerCostGold { get; private set; }
    /// <summary>
    /// 回收塔消耗金币
    /// </summary>
    public int ReclaimTowerCostGold { get; private set; }
    /// <summary>
    /// 出售塔获得金币
    /// </summary>
    public int ScaleTowerCostGold { get; private set; }
    /// <summary>
    /// 下一级id
    /// </summary>
    public string NextTowerId { get; private set; }
    public TowerDefense_TowerCfg NextTowerId_Ref { get; private set; }
    /// <summary>
    /// 升级消耗数量
    /// </summary>
    public int NewTowerCostCount { get; private set; }
    /// <summary>
    /// aiCfgId
    /// </summary>
    public string AiCfgId { get; private set; }
    /// <summary>
    /// 生成时Action事件id（对应ActionConfig文件夹下表格）
    /// </summary>
    public System.Collections.Generic.List<string> CreateActionIds { get; private set; }

    public const int __ID__ = -1994510109;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.Id_Ref = (_tables["ItemCfgCategory"] as ItemCfgCategory).GetOrDefault(Id);
        this.TutorialCfgId_Ref = (_tables["TutorialCfgCategory"] as TutorialCfgCategory).GetOrDefault(TutorialCfgId);
        UnLockCondition?.Resolve(_tables);
        Tower2UnitInfo?.Resolve(_tables);
        this.NextTowerId_Ref = (_tables["TowerDefense_TowerCfgCategory"] as TowerDefense_TowerCfgCategory).GetOrDefault(NextTowerId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        UnLockCondition?.TranslateText(translator);
        Tower2UnitInfo?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "QualityRank:" + QualityRank + ","
        + "IsShowTutorialInBattle:" + IsShowTutorialInBattle + ","
        + "MaxTiltedUpAngle:" + MaxTiltedUpAngle + ","
        + "MaxTiltedDownAngle:" + MaxTiltedDownAngle + ","
        + "TutorialCfgId:" + TutorialCfgId + ","
        + "IsShowInBattleDeckUI:" + IsShowInBattleDeckUI + ","
        + "UnLockCondition:" + UnLockCondition + ","
        + "Tower2UnitInfo:" + Tower2UnitInfo + ","
        + "BuyTowerCostGold:" + BuyTowerCostGold + ","
        + "ReclaimTowerCostGold:" + ReclaimTowerCostGold + ","
        + "ScaleTowerCostGold:" + ScaleTowerCostGold + ","
        + "NextTowerId:" + NextTowerId + ","
        + "NewTowerCostCount:" + NewTowerCostCount + ","
        + "AiCfgId:" + AiCfgId + ","
        + "CreateActionIds:" + Bright.Common.StringUtil.CollectionToString(CreateActionIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}