//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
[Config]
public partial class UnitPropertyCfgCategory: ConfigSingleton<UnitPropertyCfgCategory>
{
    private readonly List<UnitPropertyCfg> _dataList;

    private Dictionary<(string, int), UnitPropertyCfg> _dataMapUnion;

    public UnitPropertyCfgCategory(ByteBuf _buf)
    {
        _dataList = new List<UnitPropertyCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UnitPropertyCfg _v;
            _v = UnitPropertyCfg.DeserializeUnitPropertyCfg(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(string, int), UnitPropertyCfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.PropertyType, _v.Level), _v);
        }
        PostInit();
    }

    public List<UnitPropertyCfg> DataList => _dataList;

    public UnitPropertyCfg Get(string propertyType, int level) => _dataMapUnion.TryGetValue((propertyType, level), out UnitPropertyCfg __v) ? __v : null;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(UnitPropertyCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}