//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
[Config]
public partial class UnitGlobalBuffCfgCategory: ConfigSingleton<UnitGlobalBuffCfgCategory>
{
    private readonly Dictionary<string, UnitGlobalBuffCfg> _dataMap;
    private readonly List<UnitGlobalBuffCfg> _dataList;
    
    public UnitGlobalBuffCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, UnitGlobalBuffCfg>();
        _dataList = new List<UnitGlobalBuffCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UnitGlobalBuffCfg _v;
            _v = UnitGlobalBuffCfg.DeserializeUnitGlobalBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, UnitGlobalBuffCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<UnitGlobalBuffCfg> DataList => _dataList;

    public UnitGlobalBuffCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitGlobalBuffCfg Get(string key) => _dataMap[key];
    public UnitGlobalBuffCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(UnitGlobalBuffCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}