//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 花费xx钻石解锁
/// </summary>
public sealed partial class UnLockByDiamond:  UnLockConditionBase 
{
    public UnLockByDiamond(ByteBuf _buf)  : base(_buf) 
    {
        DiamondValue = _buf.ReadInt();
        PostInit();
    }

    public static UnLockByDiamond DeserializeUnLockByDiamond(ByteBuf _buf)
    {
        return new UnLockByDiamond(_buf);
    }

    /// <summary>
    /// 花费钻石数
    /// </summary>
    public int DiamondValue { get; private set; }

    public const int __ID__ = -802651687;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "DiamondValue:" + DiamondValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}