//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionGameCfg_ChgGamePlayNumeric: Bright.Config.BeanBase
{
    public ActionGameCfg_ChgGamePlayNumeric(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        GameNumericType = (GameNumericType)_buf.ReadInt();
        ChgValue = _buf.ReadFloat();
        PostInit();
    }

    public static ActionGameCfg_ChgGamePlayNumeric DeserializeActionGameCfg_ChgGamePlayNumeric(ByteBuf _buf)
    {
        return new ActionGameCfg_ChgGamePlayNumeric(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 属性类型
    /// </summary>
    public GameNumericType GameNumericType { get; private set; }
    /// <summary>
    /// 修改值
    /// </summary>
    public float ChgValue { get; private set; }

    public const int __ID__ = -1169665464;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "GameNumericType:" + GameNumericType + ","
        + "ChgValue:" + ChgValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}