//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 召唤Aoe
/// </summary>
[Config]
public partial class ActionCfg_CallAoeCategory: ConfigSingleton<ActionCfg_CallAoeCategory>
{
    private readonly Dictionary<string, ActionCfg_CallAoe> _dataMap;
    private readonly List<ActionCfg_CallAoe> _dataList;
    
    public ActionCfg_CallAoeCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, ActionCfg_CallAoe>();
        _dataList = new List<ActionCfg_CallAoe>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActionCfg_CallAoe _v;
            _v = ActionCfg_CallAoe.DeserializeActionCfg_CallAoe(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, ActionCfg_CallAoe> GetAll()
    {
        return _dataMap;
    }
    
    public List<ActionCfg_CallAoe> DataList => _dataList;

    public ActionCfg_CallAoe GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActionCfg_CallAoe Get(string key) => _dataMap[key];
    public ActionCfg_CallAoe this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(ActionCfg_CallAoe).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}