//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 矩形选择
/// </summary>
public sealed partial class ActionCallAutoUnitWhenRectangle:  ActionCallAutoUnitArea 
{
    public ActionCallAutoUnitWhenRectangle(ByteBuf _buf)  : base(_buf) 
    {
        RectangleArea = RectangleArea.DeserializeRectangleArea(_buf);
        IsChgToSelectPos = _buf.ReadBool();
        PostInit();
    }

    public static ActionCallAutoUnitWhenRectangle DeserializeActionCallAutoUnitWhenRectangle(ByteBuf _buf)
    {
        return new ActionCallAutoUnitWhenRectangle(_buf);
    }

    /// <summary>
    /// 矩形信息
    /// </summary>
    public RectangleArea RectangleArea { get; private set; }
    /// <summary>
    /// 是否转为记录成Pos位置信息(需要在特定位置施法有效,因为unit可能已走开)
    /// </summary>
    public bool IsChgToSelectPos { get; private set; }

    public const int __ID__ = -612145970;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        RectangleArea?.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        RectangleArea?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IsSave:" + IsSave + ","
        + "SelectNum:" + SelectNum + ","
        + "IsFriend:" + IsFriend + ","
        + "IsOnlyPlayer:" + IsOnlyPlayer + ","
        + "OffSetInfo:" + OffSetInfo + ","
        + "RectangleArea:" + RectangleArea + ","
        + "IsChgToSelectPos:" + IsChgToSelectPos + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}