//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_PlayAudio: Bright.Config.BeanBase
{
    public ActionCfg_PlayAudio(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        IsOnlySelfShow = _buf.ReadBool();
        ResId = _buf.ReadString();
        Duration = _buf.ReadFloat();
        IsLoop = _buf.ReadBool();
        PostInit();
    }

    public static ActionCfg_PlayAudio DeserializeActionCfg_PlayAudio(ByteBuf _buf)
    {
        return new ActionCfg_PlayAudio(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 是否进自己可见
    /// </summary>
    public bool IsOnlySelfShow { get; private set; }
    /// <summary>
    /// 资源id
    /// </summary>
    public string ResId { get; private set; }
    public ResAudioCfg ResId_Ref { get; private set; }
    /// <summary>
    /// 持续时间(s),-1表示永久
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// 是否循环播放
    /// </summary>
    public bool IsLoop { get; private set; }

    public const int __ID__ = 1680093201;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.ResId_Ref = (_tables["ResAudioCfgCategory"] as ResAudioCfgCategory).GetOrDefault(ResId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "IsOnlySelfShow:" + IsOnlySelfShow + ","
        + "ResId:" + ResId + ","
        + "Duration:" + Duration + ","
        + "IsLoop:" + IsLoop + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}