//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_PlayAnimator: Bright.Config.BeanBase
{
    public ActionCfg_PlayAnimator(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        IsOnlySelfShow = _buf.ReadBool();
        AnimatorName = (AnimatorMotionName)_buf.ReadInt();
        IsLoop = _buf.ReadBool();
        PostInit();
    }

    public static ActionCfg_PlayAnimator DeserializeActionCfg_PlayAnimator(ByteBuf _buf)
    {
        return new ActionCfg_PlayAnimator(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 是否仅自己可见
    /// </summary>
    public bool IsOnlySelfShow { get; private set; }
    /// <summary>
    /// 动作名称
    /// </summary>
    public AnimatorMotionName AnimatorName { get; private set; }
    /// <summary>
    /// 是否循环播放
    /// </summary>
    public bool IsLoop { get; private set; }

    public const int __ID__ = 631630028;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "IsOnlySelfShow:" + IsOnlySelfShow + ","
        + "AnimatorName:" + AnimatorName + ","
        + "IsLoop:" + IsLoop + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}