//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_ReplaceUnitCfgId: Bright.Config.BeanBase
{
    public ActionCfg_ReplaceUnitCfgId(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        ReplaceUnitCfgId = _buf.ReadString();
        PostInit();
    }

    public static ActionCfg_ReplaceUnitCfgId DeserializeActionCfg_ReplaceUnitCfgId(ByteBuf _buf)
    {
        return new ActionCfg_ReplaceUnitCfgId(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 替换为的unitCfgId
    /// </summary>
    public string ReplaceUnitCfgId { get; private set; }
    public UnitCfg ReplaceUnitCfgId_Ref { get; private set; }

    public const int __ID__ = -391818440;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.ReplaceUnitCfgId_Ref = (_tables["UnitCfgCategory"] as UnitCfgCategory).GetOrDefault(ReplaceUnitCfgId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ReplaceUnitCfgId:" + ReplaceUnitCfgId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}