//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_EffectRemove: Bright.Config.BeanBase
{
    public ActionCfg_EffectRemove(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Key = _buf.ReadString();
        PostInit();
    }

    public static ActionCfg_EffectRemove DeserializeActionCfg_EffectRemove(ByteBuf _buf)
    {
        return new ActionCfg_EffectRemove(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 唯一key(用来便于准确删除)
    /// </summary>
    public string Key { get; private set; }

    public const int __ID__ = 1700835334;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Key:" + Key + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}