//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_DamageChg: Bright.Config.BeanBase
{
    public ActionCfg_DamageChg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        IsPercent = _buf.ReadBool();
        ChgValue = _buf.ReadInt();
        ChgValueOperation = (ValueOperation)_buf.ReadInt();
        PostInit();
    }

    public static ActionCfg_DamageChg DeserializeActionCfg_DamageChg(ByteBuf _buf)
    {
        return new ActionCfg_DamageChg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 是否百分比
    /// </summary>
    public bool IsPercent { get; private set; }
    /// <summary>
    /// 修改的数值(都为正数)(如果是percent则是N%)
    /// </summary>
    public int ChgValue { get; private set; }
    /// <summary>
    /// 修改的操作
    /// </summary>
    public ValueOperation ChgValueOperation { get; private set; }

    public const int __ID__ = 1311261122;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IsPercent:" + IsPercent + ","
        + "ChgValue:" + ChgValue + ","
        + "ChgValueOperation:" + ChgValueOperation + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}