//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 攻击者(可能是子弹,也可能是人)
/// </summary>
public sealed partial class ActionCallOnAttackUnit:  ActionCallParam 
{
    public ActionCallOnAttackUnit(ByteBuf _buf)  : base(_buf) 
    {
        IsChgToSelectPos = _buf.ReadBool();
        PostInit();
    }

    public static ActionCallOnAttackUnit DeserializeActionCallOnAttackUnit(ByteBuf _buf)
    {
        return new ActionCallOnAttackUnit(_buf);
    }

    /// <summary>
    /// 是否转为记录成Pos位置信息(需要在特定位置施法有效,因为unit可能已走开)
    /// </summary>
    public bool IsChgToSelectPos { get; private set; }

    public const int __ID__ = -1783059681;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IsChgToSelectPos:" + IsChgToSelectPos + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}