//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_DeathShow: Bright.Config.BeanBase
{
    public ActionCfg_DeathShow(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Duration = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DeathShowActionCall = new System.Collections.Generic.List<AttackActionCall>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AttackActionCall _e0;  _e0 = AttackActionCall.DeserializeAttackActionCall(_buf); DeathShowActionCall.Add(_e0);}}
        PostInit();
    }

    public static ActionCfg_DeathShow DeserializeActionCfg_DeathShow(ByteBuf _buf)
    {
        return new ActionCfg_DeathShow(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 持续时间
    /// </summary>
    public float Duration { get; private set; }
    public System.Collections.Generic.List<AttackActionCall> DeathShowActionCall { get; private set; }

    public const int __ID__ = -1823164768;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var _e in DeathShowActionCall) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in DeathShowActionCall) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Duration:" + Duration + ","
        + "DeathShowActionCall:" + Bright.Common.StringUtil.CollectionToString(DeathShowActionCall) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}