//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 摄像机方向
/// </summary>
public abstract partial class ActionCallShow_Camera:  ActionCallCasterShow 
{
    public ActionCallShow_Camera(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static ActionCallShow_Camera DeserializeActionCallShow_Camera(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case ActionCallShow_Camera_OtherUnit.__ID__: return new ActionCallShow_Camera_OtherUnit(_buf);
            case ActionCallShow_Camera_OtherArea.__ID__: return new ActionCallShow_Camera_OtherArea(_buf);
            case ActionCallShow_Camera_RectangleArea.__ID__: return new ActionCallShow_Camera_RectangleArea(_buf);
            case ActionCallShow_Camera_UmbellateArea.__ID__: return new ActionCallShow_Camera_UmbellateArea(_buf);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}