//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_BuffResetDuration: Bright.Config.BeanBase
{
    public ActionCfg_BuffResetDuration(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        BuffDurationChgType = BuffDurationChgType.DeserializeBuffDurationChgType(_buf);
        PostInit();
    }

    public static ActionCfg_BuffResetDuration DeserializeActionCfg_BuffResetDuration(ByteBuf _buf)
    {
        return new ActionCfg_BuffResetDuration(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    public BuffDurationChgType BuffDurationChgType { get; private set; }

    public const int __ID__ = -428343681;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        BuffDurationChgType?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        BuffDurationChgType?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BuffDurationChgType:" + BuffDurationChgType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}