//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 创建飘字
/// </summary>
[Config]
public partial class ActionCfg_FloatingTextCategory: ConfigSingleton<ActionCfg_FloatingTextCategory>
{
    private readonly Dictionary<string, ActionCfg_FloatingText> _dataMap;
    private readonly List<ActionCfg_FloatingText> _dataList;
    
    public ActionCfg_FloatingTextCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, ActionCfg_FloatingText>();
        _dataList = new List<ActionCfg_FloatingText>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActionCfg_FloatingText _v;
            _v = ActionCfg_FloatingText.DeserializeActionCfg_FloatingText(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, ActionCfg_FloatingText> GetAll()
    {
        return _dataMap;
    }
    
    public List<ActionCfg_FloatingText> DataList => _dataList;

    public ActionCfg_FloatingText GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActionCfg_FloatingText Get(string key) => _dataMap[key];
    public ActionCfg_FloatingText this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(ActionCfg_FloatingText).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}