//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_BuffDeal: Bright.Config.BeanBase
{
    public ActionCfg_BuffDeal(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        BuffDealSelectCondition = BuffDealSelectCondition.DeserializeBuffDealSelectCondition(_buf);
        BuffDealType = BuffDealType.DeserializeBuffDealType(_buf);
        PostInit();
    }

    public static ActionCfg_BuffDeal DeserializeActionCfg_BuffDeal(ByteBuf _buf)
    {
        return new ActionCfg_BuffDeal(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 对Buff的选择
    /// </summary>
    public BuffDealSelectCondition BuffDealSelectCondition { get; private set; }
    /// <summary>
    /// 对Buff的操作
    /// </summary>
    public BuffDealType BuffDealType { get; private set; }

    public const int __ID__ = -437546384;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        BuffDealSelectCondition?.Resolve(_tables);
        BuffDealType?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        BuffDealSelectCondition?.TranslateText(translator);
        BuffDealType?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BuffDealSelectCondition:" + BuffDealSelectCondition + ","
        + "BuffDealType:" + BuffDealType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}