//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 子弹(Buff)的递归发送者(一定是player或monster)
/// </summary>
public sealed partial class ActionCallCasterPlayerUnit:  ActionCallParam 
{
    public ActionCallCasterPlayerUnit(ByteBuf _buf)  : base(_buf) 
    {
        IsChgToSelectPos = _buf.ReadBool();
        PostInit();
    }

    public static ActionCallCasterPlayerUnit DeserializeActionCallCasterPlayerUnit(ByteBuf _buf)
    {
        return new ActionCallCasterPlayerUnit(_buf);
    }

    /// <summary>
    /// 是否转为记录成Pos位置信息(需要在特定位置施法有效,因为unit可能已走开)
    /// </summary>
    public bool IsChgToSelectPos { get; private set; }

    public const int __ID__ = 1606038341;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IsChgToSelectPos:" + IsChgToSelectPos + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}