//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// Aoe触发事件
    /// </summary>
    public enum AoeTriggerEvent
    {
        /// <summary>
        /// 监听 Aoe被创建的事件
        /// </summary>
        AoeOnCreate = 1,
        /// <summary>
        /// 监听 进入Aoe的事件
        /// </summary>
        AoeOnEnter = 2,
        /// <summary>
        /// 监听 退出Aoe的事件
        /// </summary>
        AoeOnExist = 3,
        /// <summary>
        /// 监听 Aoe被销毁的事件
        /// </summary>
        AoeOnRemoved = 4,
        /// <summary>
        /// 监听 Aoe在每个工作周期会执行的函数
        /// </summary>
        AoeOnTick1 = 5,
        /// <summary>
        /// 监听 Aoe在每个工作周期会执行的函数
        /// </summary>
        AoeOnTick2 = 6,
        /// <summary>
        /// 监听 Aoe在每个工作周期会执行的函数
        /// </summary>
        AoeOnTick3 = 7,
    }

} 
