//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public abstract partial class BuffRemoveType: Bright.Config.BeanBase
{
    public BuffRemoveType(ByteBuf _buf) 
    {
        PostInit();
    }

    public static BuffRemoveType DeserializeBuffRemoveType(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case BuffRemoveCur.__ID__: return new BuffRemoveCur(_buf);
            case BuffRemoveByTag.__ID__: return new BuffRemoveByTag(_buf);
            case BuffRemoveByTagGroup.__ID__: return new BuffRemoveByTagGroup(_buf);
            case BuffRemoveByType.__ID__: return new BuffRemoveByType(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}