//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 匹配buffType
/// </summary>
public sealed partial class ByBuffType:  BuffDealSelectCondition 
{
    public ByBuffType(ByteBuf _buf)  : base(_buf) 
    {
        BuffType = (BuffType)_buf.ReadInt();
        PostInit();
    }

    public static ByBuffType DeserializeByBuffType(ByteBuf _buf)
    {
        return new ByBuffType(_buf);
    }

    public BuffType BuffType { get; private set; }

    public const int __ID__ = -1201539132;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffType:" + BuffType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}