//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 匹配buffCfgId
/// </summary>
public sealed partial class ByBuffCfgId:  BuffDealSelectCondition 
{
    public ByBuffCfgId(ByteBuf _buf)  : base(_buf) 
    {
        BuffCfgId = _buf.ReadString();
        PostInit();
    }

    public static ByBuffCfgId DeserializeByBuffCfgId(ByteBuf _buf)
    {
        return new ByBuffCfgId(_buf);
    }

    public string BuffCfgId { get; private set; }
    public BuffCfg BuffCfgId_Ref { get; private set; }

    public const int __ID__ = 1390717269;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        this.BuffCfgId_Ref = (_tables["BuffCfgCategory"] as BuffCfgCategory).GetOrDefault(BuffCfgId);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffCfgId:" + BuffCfgId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}