//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 货币类型(战斗内)
    /// </summary>
    public enum CoinTypeInGame
    {
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 1,
    }

} 
