//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 功能菜单
/// </summary>
[Config]
public partial class FunctionMenuCfgCategory: ConfigSingleton<FunctionMenuCfgCategory>
{
    private readonly Dictionary<string, FunctionMenuCfg> _dataMap;
    private readonly List<FunctionMenuCfg> _dataList;
    
    public FunctionMenuCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, FunctionMenuCfg>();
        _dataList = new List<FunctionMenuCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FunctionMenuCfg _v;
            _v = FunctionMenuCfg.DeserializeFunctionMenuCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, FunctionMenuCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<FunctionMenuCfg> DataList => _dataList;

    public FunctionMenuCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FunctionMenuCfg Get(string key) => _dataMap[key];
    public FunctionMenuCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(FunctionMenuCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}