//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 存活无尽模式第N波
/// </summary>
public sealed partial class FunctionMenuConditionIndexWhenAREndlessChallenge:  FunctionMenuCondition 
{
    public FunctionMenuConditionIndexWhenAREndlessChallenge(ByteBuf _buf)  : base(_buf) 
    {
        Index = _buf.ReadInt();
        PostInit();
    }

    public static FunctionMenuConditionIndexWhenAREndlessChallenge DeserializeFunctionMenuConditionIndexWhenAREndlessChallenge(ByteBuf _buf)
    {
        return new FunctionMenuConditionIndexWhenAREndlessChallenge(_buf);
    }

    /// <summary>
    /// 无尽模式第N波
    /// </summary>
    public int Index { get; private set; }

    public const int __ID__ = -1095197624;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}