//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 闪烁
/// </summary>
public sealed partial class GameObjectFlicker:  GameObjectDeal 
{
    public GameObjectFlicker(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static GameObjectFlicker DeserializeGameObjectFlicker(ByteBuf _buf)
    {
        return new GameObjectFlicker(_buf);
    }


    public const int __ID__ = 1746894535;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}