//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 塔防(无尽模式)
/// </summary>
public sealed partial class GamePlayTowerDefenseEndlessChallenge:  GamePlayTowerDefenseEndlessChallengeMonster 
{
    public GamePlayTowerDefenseEndlessChallenge(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static GamePlayTowerDefenseEndlessChallenge DeserializeGamePlayTowerDefenseEndlessChallenge(ByteBuf _buf)
    {
        return new GamePlayTowerDefenseEndlessChallenge(_buf);
    }


    public const int __ID__ = -1943758740;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "GamePlayModeCfgId:" + GamePlayModeCfgId + ","
        + "RepeatNum:" + RepeatNum + ","
        + "MonsterWaveNumScalePercentCoefficient:" + MonsterWaveNumScalePercentCoefficient + ","
        + "MonsterWaveLevelScalePercentCoefficient:" + MonsterWaveLevelScalePercentCoefficient + ","
        + "WaveRewardGoldScalePercentCoefficient:" + WaveRewardGoldScalePercentCoefficient + ","
        + "CreateActionIds:" + Bright.Common.StringUtil.CollectionToString(CreateActionIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}