//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 物品子类型
    /// </summary>
    public enum ItemSubType
    {
        /// <summary>
        /// 任意
        /// </summary>
        None = -1,
        /// <summary>
        /// 塔
        /// </summary>
        AttackTower = 0,
        /// <summary>
        /// 陷阱
        /// </summary>
        Trap = 1,
        /// <summary>
        /// 召唤怪物
        /// </summary>
        CallMonster = 2,
        /// <summary>
        /// 怪物1
        /// </summary>
        Monster1 = 0,
        /// <summary>
        /// 头像框系列1
        /// </summary>
        AvatarFrameType1 = 0,
        /// <summary>
        /// 钻石
        /// </summary>
        Diamond = 0,
        /// <summary>
        /// 街机代币
        /// </summary>
        ArcadeCoin = 1,
    }

} 
