//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 物品表
/// </summary>
[Config]
public partial class ItemCfgCategory: ConfigSingleton<ItemCfgCategory>
{
    private readonly Dictionary<string, ItemCfg> _dataMap;
    private readonly List<ItemCfg> _dataList;
    
    public ItemCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, ItemCfg>();
        _dataList = new List<ItemCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ItemCfg _v;
            _v = ItemCfg.DeserializeItemCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, ItemCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<ItemCfg> DataList => _dataList;

    public ItemCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemCfg Get(string key) => _dataMap[key];
    public ItemCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(ItemCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}