//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 天赋表
/// </summary>
[Config]
public partial class ItemGiftCfgCategory: ConfigSingleton<ItemGiftCfgCategory>
{
    private readonly Dictionary<string, ItemGiftCfg> _dataMap;
    private readonly List<ItemGiftCfg> _dataList;
    
    public ItemGiftCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, ItemGiftCfg>();
        _dataList = new List<ItemGiftCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ItemGiftCfg _v;
            _v = ItemGiftCfg.DeserializeItemGiftCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, ItemGiftCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<ItemGiftCfg> DataList => _dataList;

    public ItemGiftCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemGiftCfg Get(string key) => _dataMap[key];
    public ItemGiftCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(ItemGiftCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}