//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
[Config]
public partial class MonsterWaveCallCfgCategory: ConfigSingleton<MonsterWaveCallCfgCategory>
{
    private readonly List<MonsterWaveCallCfg> _dataList;

    private Dictionary<(string, int), MonsterWaveCallCfg> _dataMapUnion;

    public MonsterWaveCallCfgCategory(ByteBuf _buf)
    {
        _dataList = new List<MonsterWaveCallCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MonsterWaveCallCfg _v;
            _v = MonsterWaveCallCfg.DeserializeMonsterWaveCallCfg(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(string, int), MonsterWaveCallCfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.WaveRule, _v.WaveIndex), _v);
        }
        PostInit();
    }

    public List<MonsterWaveCallCfg> DataList => _dataList;

    public MonsterWaveCallCfg Get(string waveRule, int waveIndex) => _dataMapUnion.TryGetValue((waveRule, waveIndex), out MonsterWaveCallCfg __v) ? __v : null;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(MonsterWaveCallCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}