//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class MonsterWaveCallCfg: Bright.Config.BeanBase
{
    public MonsterWaveCallCfg(ByteBuf _buf) 
    {
        WaveRule = _buf.ReadString();
        WaveIndex = _buf.ReadInt();
        Name = _buf.ReadString();
        Duration = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Nodes = new System.Collections.Generic.List<MonsterWaveCallNode>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MonsterWaveCallNode _e0;  _e0 = MonsterWaveCallNode.DeserializeMonsterWaveCallNode(_buf); Nodes.Add(_e0);}}
        PostInit();
    }

    public static MonsterWaveCallCfg DeserializeMonsterWaveCallCfg(ByteBuf _buf)
    {
        return new MonsterWaveCallCfg(_buf);
    }

    /// <summary>
    /// 刷怪规则
    /// </summary>
    public string WaveRule { get; private set; }
    /// <summary>
    /// 波次
    /// </summary>
    public int WaveIndex { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 总时长(单位秒)
    /// </summary>
    public float Duration { get; private set; }
    public System.Collections.Generic.List<MonsterWaveCallNode> Nodes { get; private set; }

    public const int __ID__ = 1139606483;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var _e in Nodes) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Nodes) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "WaveRule:" + WaveRule + ","
        + "WaveIndex:" + WaveIndex + ","
        + "Name:" + Name + ","
        + "Duration:" + Duration + ","
        + "Nodes:" + Bright.Common.StringUtil.CollectionToString(Nodes) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}