//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 属性(枚举值要和程序代码对应上)
    /// </summary>
    public enum NumericType
    {
        /// <summary>
        /// 速度
        /// </summary>
        SpeedBase = 10011,
        SpeedAdd = 10012,
        SpeedPct = 10013,
        SpeedFinalAdd = 10014,
        SpeedFinalPct = 10015,
        /// <summary>
        /// 总血量
        /// </summary>
        MaxHpBase = 10031,
        MaxHpAdd = 10032,
        MaxHpPct = 10033,
        MaxHpFinalAdd = 10034,
        MaxHpFinalPct = 10035,
        /// <summary>
        /// 物理攻击
        /// </summary>
        PhysicalAttackBase = 10051,
        PhysicalAttackAdd = 10052,
        PhysicalAttackPct = 10053,
        PhysicalAttackFinalAdd = 10054,
        PhysicalAttackFinalPct = 10055,
    }

} 
