//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 是否能被Bullet攻击
/// </summary>
public sealed partial class OnChkCanHitByBulletCondition:  Condition 
{
    public OnChkCanHitByBulletCondition(ByteBuf _buf)  : base(_buf) 
    {
        CanHit = _buf.ReadBool();
        PostInit();
    }

    public static OnChkCanHitByBulletCondition DeserializeOnChkCanHitByBulletCondition(ByteBuf _buf)
    {
        return new OnChkCanHitByBulletCondition(_buf);
    }

    public bool CanHit { get; private set; }

    public const int __ID__ = 903864152;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "CanHit:" + CanHit + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}