//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 攻击时,是否暴击
/// </summary>
public sealed partial class OnHitChkIsCriticalStrikeCondition:  UnitConditionBase 
{
    public OnHitChkIsCriticalStrikeCondition(ByteBuf _buf)  : base(_buf) 
    {
        IsCriticalStrike = _buf.ReadBool();
        PostInit();
    }

    public static OnHitChkIsCriticalStrikeCondition DeserializeOnHitChkIsCriticalStrikeCondition(ByteBuf _buf)
    {
        return new OnHitChkIsCriticalStrikeCondition(_buf);
    }

    public bool IsCriticalStrike { get; private set; }

    public const int __ID__ = 2081493134;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "IsCriticalStrike:" + IsCriticalStrike + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}