//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 判断召唤对象的数量
/// </summary>
public sealed partial class OwerCountRecordCondition:  UnitConditionBase 
{
    public OwerCountRecordCondition(ByteBuf _buf)  : base(_buf) 
    {
        OwnActor = _buf.ReadBool();
        OwnBullet = _buf.ReadBool();
        OwnAoe = _buf.ReadBool();
        OwnSkillCaster = _buf.ReadBool();
        RecordKey = (RecordKeyInt)_buf.ReadInt();
        PostInit();
    }

    public static OwerCountRecordCondition DeserializeOwerCountRecordCondition(ByteBuf _buf)
    {
        return new OwerCountRecordCondition(_buf);
    }

    /// <summary>
    /// 对象
    /// </summary>
    public bool OwnActor { get; private set; }
    /// <summary>
    /// 子弹
    /// </summary>
    public bool OwnBullet { get; private set; }
    /// <summary>
    /// aoe
    /// </summary>
    public bool OwnAoe { get; private set; }
    /// <summary>
    /// skillCaster
    /// </summary>
    public bool OwnSkillCaster { get; private set; }
    /// <summary>
    /// 数值
    /// </summary>
    public RecordKeyInt RecordKey { get; private set; }

    public const int __ID__ = -393924848;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "OwnActor:" + OwnActor + ","
        + "OwnBullet:" + OwnBullet + ","
        + "OwnAoe:" + OwnAoe + ","
        + "OwnSkillCaster:" + OwnSkillCaster + ","
        + "RecordKey:" + RecordKey + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}