//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ResUnitCfg: Bright.Config.BeanBase
{
    public ResUnitCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        MoveShowNatureSpeed = _buf.ReadFloat();
        ResName = _buf.ReadString();
        PostInit();
    }

    public static ResUnitCfg DeserializeResUnitCfg(ByteBuf _buf)
    {
        return new ResUnitCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 多少速度时Move动作最自然
    /// </summary>
    public float MoveShowNatureSpeed { get; private set; }
    /// <summary>
    /// 资源路径
    /// </summary>
    public string ResName { get; private set; }

    public const int __ID__ = -1160685664;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MoveShowNatureSpeed:" + MoveShowNatureSpeed + ","
        + "ResName:" + ResName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}