//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 目标选择对象类型
    /// </summary>
    public enum SelectObjectUnitType
    {
        /// <summary>
        /// 不限制
        /// </summary>
        All = 1,
        /// <summary>
        /// 仅玩家
        /// </summary>
        OnlyPlayer = 2,
        /// <summary>
        /// 非玩家
        /// </summary>
        NotPlayer = 3,
    }

} 
