//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 定向目标轨迹(实时面向目标)
/// </summary>
public sealed partial class TargetMoveTweenType:  SpeedMoveTweenType 
{
    public TargetMoveTweenType(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static TargetMoveTweenType DeserializeTargetMoveTweenType(ByteBuf _buf)
    {
        return new TargetMoveTweenType(_buf);
    }


    public const int __ID__ = 132977987;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "HoldTime:" + HoldTime + ","
        + "Speed:" + Speed + ","
        + "AcceleratedSpeed:" + AcceleratedSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}