//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 塔类型
    /// </summary>
    public enum TowerType
    {
        None = 0,
        /// <summary>
        /// 箭塔
        /// </summary>
        Arrow = 1,
        /// <summary>
        /// 炮塔
        /// </summary>
        Canon = 2,
    }

} 
