//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TowerDefense_BuyTowerRefreshRuleCfg: Bright.Config.BeanBase
{
    public TowerDefense_BuyTowerRefreshRuleCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        IsUseMyTowers = _buf.ReadBool();
        MyTowersWeight = _buf.ReadInt();
        IsUseMySkills = _buf.ReadBool();
        MySkillsWeight = _buf.ReadInt();
        IsUseMyMonsterCalls = _buf.ReadBool();
        MyMonsterCallsWeight = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TowerWeight = new System.Collections.Generic.List<TowerRefreshRuleOne>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { TowerRefreshRuleOne _e0;  _e0 = TowerRefreshRuleOne.DeserializeTowerRefreshRuleOne(_buf); TowerWeight.Add(_e0);}}
        PostInit();
    }

    public static TowerDefense_BuyTowerRefreshRuleCfg DeserializeTowerDefense_BuyTowerRefreshRuleCfg(ByteBuf _buf)
    {
        return new TowerDefense_BuyTowerRefreshRuleCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 是否使用自身拥有塔卡
    /// </summary>
    public bool IsUseMyTowers { get; private set; }
    /// <summary>
    /// 自身拥有塔卡的单卡权重
    /// </summary>
    public int MyTowersWeight { get; private set; }
    /// <summary>
    /// 是否使用自身拥有技能卡
    /// </summary>
    public bool IsUseMySkills { get; private set; }
    /// <summary>
    /// 自身拥有技能卡的单卡权重
    /// </summary>
    public int MySkillsWeight { get; private set; }
    /// <summary>
    /// 是否使用自身拥有怪物召唤卡
    /// </summary>
    public bool IsUseMyMonsterCalls { get; private set; }
    /// <summary>
    /// 自身拥有怪物召唤卡的单卡权重
    /// </summary>
    public int MyMonsterCallsWeight { get; private set; }
    public System.Collections.Generic.List<TowerRefreshRuleOne> TowerWeight { get; private set; }

    public const int __ID__ = -621375048;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var _e in TowerWeight) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in TowerWeight) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "IsUseMyTowers:" + IsUseMyTowers + ","
        + "MyTowersWeight:" + MyTowersWeight + ","
        + "IsUseMySkills:" + IsUseMySkills + ","
        + "MySkillsWeight:" + MySkillsWeight + ","
        + "IsUseMyMonsterCalls:" + IsUseMyMonsterCalls + ","
        + "MyMonsterCallsWeight:" + MyMonsterCallsWeight + ","
        + "TowerWeight:" + Bright.Common.StringUtil.CollectionToString(TowerWeight) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}