//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 中途休息
/// </summary>
public sealed partial class TowerDefenseBattleWithRest:  TowerDefenseBattleMonsterWaveCall 
{
    public TowerDefenseBattleWithRest(ByteBuf _buf)  : base(_buf) 
    {
        RestTime = _buf.ReadFloat();
        PostInit();
    }

    public static TowerDefenseBattleWithRest DeserializeTowerDefenseBattleWithRest(ByteBuf _buf)
    {
        return new TowerDefenseBattleWithRest(_buf);
    }

    /// <summary>
    /// 中间休息时间
    /// </summary>
    public float RestTime { get; private set; }

    public const int __ID__ = -758150775;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "MonsterWaveCallRuleCfgId:" + MonsterWaveCallRuleCfgId + ","
        + "MonsterWaveCallStartWaveIndex:" + MonsterWaveCallStartWaveIndex + ","
        + "RestTime:" + RestTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}