//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 玩法_塔防_刷怪配置
/// </summary>
[Config]
public partial class TowerDefense_MonsterWaveCallRuleCfgCategory: ConfigSingleton<TowerDefense_MonsterWaveCallRuleCfgCategory>
{
    private readonly List<TowerDefense_MonsterWaveCallRuleCfg> _dataList;

    private Dictionary<(string, int), TowerDefense_MonsterWaveCallRuleCfg> _dataMapUnion;

    public TowerDefense_MonsterWaveCallRuleCfgCategory(ByteBuf _buf)
    {
        _dataList = new List<TowerDefense_MonsterWaveCallRuleCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerDefense_MonsterWaveCallRuleCfg _v;
            _v = TowerDefense_MonsterWaveCallRuleCfg.DeserializeTowerDefense_MonsterWaveCallRuleCfg(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(string, int), TowerDefense_MonsterWaveCallRuleCfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.WaveRule, _v.WaveIndex), _v);
        }
        PostInit();
    }

    public List<TowerDefense_MonsterWaveCallRuleCfg> DataList => _dataList;

    public TowerDefense_MonsterWaveCallRuleCfg Get(string waveRule, int waveIndex) => _dataMapUnion.TryGetValue((waveRule, waveIndex), out TowerDefense_MonsterWaveCallRuleCfg __v) ? __v : null;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(TowerDefense_MonsterWaveCallRuleCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}