//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 玩法_塔防_塔配置
/// </summary>
[Config]
public partial class TowerDefense_TowerCfgCategory: ConfigSingleton<TowerDefense_TowerCfgCategory>
{
    private readonly Dictionary<string, TowerDefense_TowerCfg> _dataMap;
    private readonly List<TowerDefense_TowerCfg> _dataList;
    
    public TowerDefense_TowerCfgCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, TowerDefense_TowerCfg>();
        _dataList = new List<TowerDefense_TowerCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TowerDefense_TowerCfg _v;
            _v = TowerDefense_TowerCfg.DeserializeTowerDefense_TowerCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, TowerDefense_TowerCfg> GetAll()
    {
        return _dataMap;
    }
    
    public List<TowerDefense_TowerCfg> DataList => _dataList;

    public TowerDefense_TowerCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TowerDefense_TowerCfg Get(string key) => _dataMap[key];
    public TowerDefense_TowerCfg this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(TowerDefense_TowerCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}