//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 伞型
/// </summary>
public sealed partial class UmbellateArea:  AreaType 
{
    public UmbellateArea(ByteBuf _buf)  : base(_buf) 
    {
        Radius = _buf.ReadFloat();
        Angle = _buf.ReadFloat();
        PostInit();
    }

    public static UmbellateArea DeserializeUmbellateArea(ByteBuf _buf)
    {
        return new UmbellateArea(_buf);
    }

    /// <summary>
    /// 搜索半径
    /// </summary>
    public float Radius { get; private set; }
    /// <summary>
    /// 伞型张开的角度(单位度)(360则为圆形)
    /// </summary>
    public float Angle { get; private set; }

    public const int __ID__ = 258312740;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IgnoringHeight:" + IgnoringHeight + ","
        + "KeepHorizontal:" + KeepHorizontal + ","
        + "Radius:" + Radius + ","
        + "Angle:" + Angle + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}