//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 使用召唤者当前属性
/// </summary>
public sealed partial class UseCallerCurAttr:  BeCallActorAttrType 
{
    public UseCallerCurAttr(ByteBuf _buf)  : base(_buf) 
    {
        IsUseCallerSpeed = _buf.ReadBool();
        PostInit();
    }

    public static UseCallerCurAttr DeserializeUseCallerCurAttr(ByteBuf _buf)
    {
        return new UseCallerCurAttr(_buf);
    }

    /// <summary>
    /// 是否使用召唤者的移动速度
    /// </summary>
    public bool IsUseCallerSpeed { get; private set; }

    public const int __ID__ = -47874017;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IsUseCallerSpeed:" + IsUseCallerSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}