namespace ET
{
    public enum UIRedDotType
    {
        None,
        Root,
        Settings,
        Tutorial,
        BattleDeck,
        Cards,
        Skills,
        TowerNew,
        SkillNew,
        AvatarFrameNew,
        Bags,
        ItemOtherNew,
        Account,
        Icon,
        Mail,
        Questionnaire,
        Season,
        SeasonBringUp,
        PVE,
        PVESeason,
        Store,
        NewSeasonNotice,
        MultPlayers,
    }
}