//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_FireBullet: Bright.Config.BeanBase
{
    public ActionCfg_FireBullet(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        BulletId = _buf.ReadString();
        Duration = _buf.ReadFloat();
        OffSetInfo = OffSetInfo.DeserializeOffSetInfo(_buf);
        MoveType = MoveTweenType.DeserializeMoveTweenType(_buf);
        PostInit();
    }

    public static ActionCfg_FireBullet DeserializeActionCfg_FireBullet(ByteBuf _buf)
    {
        return new ActionCfg_FireBullet(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 子弹Id
    /// </summary>
    public string BulletId { get; private set; }
    public BulletCfg BulletId_Ref { get; private set; }
    /// <summary>
    /// 持续时间(s)
    /// </summary>
    public float Duration { get; private set; }
    public OffSetInfo OffSetInfo { get; private set; }
    public MoveTweenType MoveType { get; private set; }

    public const int __ID__ = -1637484119;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.BulletId_Ref = (_tables["BulletCfgCategory"] as BulletCfgCategory).GetOrDefault(BulletId);
        OffSetInfo?.Resolve(_tables);
        MoveType?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        OffSetInfo?.TranslateText(translator);
        MoveType?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "BulletId:" + BulletId + ","
        + "Duration:" + Duration + ","
        + "OffSetInfo:" + OffSetInfo + ","
        + "MoveType:" + MoveType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}