//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 播放新的timeline(对自身或他人都有效)
/// </summary>
[Config]
public partial class ActionCfg_TimelinePlayCategory: ConfigSingleton<ActionCfg_TimelinePlayCategory>
{
    private readonly Dictionary<string, ActionCfg_TimelinePlay> _dataMap;
    private readonly List<ActionCfg_TimelinePlay> _dataList;
    
    public ActionCfg_TimelinePlayCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, ActionCfg_TimelinePlay>();
        _dataList = new List<ActionCfg_TimelinePlay>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActionCfg_TimelinePlay _v;
            _v = ActionCfg_TimelinePlay.DeserializeActionCfg_TimelinePlay(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, ActionCfg_TimelinePlay> GetAll()
    {
        return _dataMap;
    }
    
    public List<ActionCfg_TimelinePlay> DataList => _dataList;

    public ActionCfg_TimelinePlay GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActionCfg_TimelinePlay Get(string key) => _dataMap[key];
    public ActionCfg_TimelinePlay this[string key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(ActionCfg_TimelinePlay).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}