//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionCfg_FireBullet: Bright.Config.BeanBase
{
    public ActionCfg_FireBullet(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ResId = _buf.ReadString();
        MoveType = _buf.ReadString();
        PostInit();
    }

    public static ActionCfg_FireBullet DeserializeActionCfg_FireBullet(ByteBuf _buf)
    {
        return new ActionCfg_FireBullet(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 资源id
    /// </summary>
    public string ResId { get; private set; }
    public BulletCfg ResId_Ref { get; private set; }
    /// <summary>
    /// 飞行轨迹
    /// </summary>
    public string MoveType { get; private set; }

    public const int __ID__ = -1637484119;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.ResId_Ref = (_tables["BulletCfgCategory"] as BulletCfgCategory).GetOrDefault(ResId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "ResId:" + ResId + ","
        + "MoveType:" + MoveType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}