//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 仅ActionCfg_AttackArea中使用,表示使用调用时传入的对象进行处理
/// </summary>
public sealed partial class ActionCallAutoUnitOne:  ActionCallAutoUnit 
{
    public ActionCallAutoUnitOne(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static ActionCallAutoUnitOne DeserializeActionCallAutoUnitOne(ByteBuf _buf)
    {
        return new ActionCallAutoUnitOne(_buf);
    }


    public const int __ID__ = 1961149215;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "IsSave:" + IsSave + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}