//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class ActionGameCfg_CreateGlobalUnit: Bright.Config.BeanBase
{
    public ActionGameCfg_CreateGlobalUnit(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        UnitId = _buf.ReadString();
        Level = _buf.ReadInt();
        CallCount = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BeCallActorActionId = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); BeCallActorActionId.Add(_e0);}}
        UnitAiCfg = _buf.ReadString();
        Duration = _buf.ReadFloat();
        CallActorUnitType = (CallActorUnitType)_buf.ReadInt();
        CallActorTeamFlagType = (CallActorTeamFlagType)_buf.ReadInt();
        CallActorPositionType = (CallActorPositionType)_buf.ReadInt();
        PostInit();
    }

    public static ActionGameCfg_CreateGlobalUnit DeserializeActionGameCfg_CreateGlobalUnit(ByteBuf _buf)
    {
        return new ActionGameCfg_CreateGlobalUnit(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// unit_id
    /// </summary>
    public string UnitId { get; private set; }
    public UnitCfg UnitId_Ref { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 召唤的数量
    /// </summary>
    public int CallCount { get; private set; }
    /// <summary>
    /// 被召唤时的Action事件
    /// </summary>
    public System.Collections.Generic.List<string> BeCallActorActionId { get; private set; }
    /// <summary>
    /// AICfgId
    /// </summary>
    public string UnitAiCfg { get; private set; }
    /// <summary>
    /// 持续时间(s)(-1表示永久)
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// callActor Unit类型
    /// </summary>
    public CallActorUnitType CallActorUnitType { get; private set; }
    /// <summary>
    /// callActor阵营类型
    /// </summary>
    public CallActorTeamFlagType CallActorTeamFlagType { get; private set; }
    /// <summary>
    /// callActor生成位置
    /// </summary>
    public CallActorPositionType CallActorPositionType { get; private set; }

    public const int __ID__ = 1066480646;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        this.UnitId_Ref = (_tables["UnitCfgCategory"] as UnitCfgCategory).GetOrDefault(UnitId);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "UnitId:" + UnitId + ","
        + "Level:" + Level + ","
        + "CallCount:" + CallCount + ","
        + "BeCallActorActionId:" + Bright.Common.StringUtil.CollectionToString(BeCallActorActionId) + ","
        + "UnitAiCfg:" + UnitAiCfg + ","
        + "Duration:" + Duration + ","
        + "CallActorUnitType:" + CallActorUnitType + ","
        + "CallActorTeamFlagType:" + CallActorTeamFlagType + ","
        + "CallActorPositionType:" + CallActorPositionType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}