//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 对象选择器
/// </summary>
public abstract partial class ActionCallParam: Bright.Config.BeanBase
{
    public ActionCallParam(ByteBuf _buf) 
    {
        PostInit();
    }

    public static ActionCallParam DeserializeActionCallParam(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case ActionCallSelectLast.__ID__: return new ActionCallSelectLast(_buf);
            case ActionCallShow_Self_Unit.__ID__: return new ActionCallShow_Self_Unit(_buf);
            case ActionCallShow_Self_Area.__ID__: return new ActionCallShow_Self_Area(_buf);
            case ActionCallShow_Self_OtherUnit.__ID__: return new ActionCallShow_Self_OtherUnit(_buf);
            case ActionCallShow_Self_OtherArea.__ID__: return new ActionCallShow_Self_OtherArea(_buf);
            case ActionCallShow_Self_RectangleArea.__ID__: return new ActionCallShow_Self_RectangleArea(_buf);
            case ActionCallShow_Self_UmbellateArea.__ID__: return new ActionCallShow_Self_UmbellateArea(_buf);
            case ActionCallShow_Camera_Unit.__ID__: return new ActionCallShow_Camera_Unit(_buf);
            case ActionCallShow_Camera_Area.__ID__: return new ActionCallShow_Camera_Area(_buf);
            case ActionCallShow_Camera_RectangleArea.__ID__: return new ActionCallShow_Camera_RectangleArea(_buf);
            case ActionCallShow_Camera_UmbellateArea.__ID__: return new ActionCallShow_Camera_UmbellateArea(_buf);
            case ActionCallAutoSelf.__ID__: return new ActionCallAutoSelf(_buf);
            case ActionCallAutoUnitWhenUmbellate.__ID__: return new ActionCallAutoUnitWhenUmbellate(_buf);
            case ActionCallAutoUnitWhenRectangle.__ID__: return new ActionCallAutoUnitWhenRectangle(_buf);
            case ActionCallOnAoeChgUnit.__ID__: return new ActionCallOnAoeChgUnit(_buf);
            case ActionCallOnAoeInUnit.__ID__: return new ActionCallOnAoeInUnit(_buf);
            case ActionCallCasterUnit.__ID__: return new ActionCallCasterUnit(_buf);
            case ActionCallCasterFirstActorUnit.__ID__: return new ActionCallCasterFirstActorUnit(_buf);
            case ActionCallCasterActorUnit.__ID__: return new ActionCallCasterActorUnit(_buf);
            case ActionCallOnAttackUnit.__ID__: return new ActionCallOnAttackUnit(_buf);
            case ActionCallBeHurtUnit.__ID__: return new ActionCallBeHurtUnit(_buf);
            case ActionCallOwnCaller.__ID__: return new ActionCallOwnCaller(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}