//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// AI配置表
/// </summary>
[Config]
public partial class AICfgCategory: ConfigSingleton<AICfgCategory>
{
    private readonly List<AICfg> _dataList;

    private Dictionary<(string, int), AICfg> _dataMapUnion;

    public AICfgCategory(ByteBuf _buf)
    {
        _dataList = new List<AICfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AICfg _v;
            _v = AICfg.DeserializeAICfg(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(string, int), AICfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.AIConfigId, _v.Order), _v);
        }
        PostInit();
    }

    public List<AICfg> DataList => _dataList;

    public AICfg Get(string AIConfigId, int Order) => _dataMapUnion.TryGetValue((AIConfigId, Order), out AICfg __v) ? __v : null;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(AICfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}