//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 动画名称
    /// </summary>
    public enum AnimatorMotionName
    {
        None = 1,
        Idle = 2,
        Move = 3,
        Fly = 4,
        Attack1 = 5,
        Skill1 = 6,
        Skill2 = 7,
        Die = 8,
        Show = 9,
        HideToIdle = 10,
        Underground = 11,
    }

} 
