//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// Buff内容
/// </summary>
public abstract partial class BuffAction: Bright.Config.BeanBase
{
    public BuffAction(ByteBuf _buf) 
    {
        PostInit();
    }

    public static BuffAction DeserializeBuffAction(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case BuffActionNone.__ID__: return new BuffActionNone(_buf);
            case BuffActionModifyAttribute.__ID__: return new BuffActionModifyAttribute(_buf);
            case BuffActionModifyAttributeByWaveIndex.__ID__: return new BuffActionModifyAttributeByWaveIndex(_buf);
            case BuffActionModifyAttributeByCircleWaveIndex.__ID__: return new BuffActionModifyAttributeByCircleWaveIndex(_buf);
            case BuffActionModifySkillAttribute.__ID__: return new BuffActionModifySkillAttribute(_buf);
            case BuffActionModifyMotionVertical.__ID__: return new BuffActionModifyMotionVertical(_buf);
            case BuffActionModifyMotionHorizontal_Forward.__ID__: return new BuffActionModifyMotionHorizontal_Forward(_buf);
            case BuffActionModifyMotionHorizontal_Back.__ID__: return new BuffActionModifyMotionHorizontal_Back(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}