//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 通过波次修改属性(float chgValue = buffActionModifyAttribute.BaseValue*waveIndex + buffActionModifyAttribute.StackValue * stackCount*waveIndex)
/// </summary>
public sealed partial class BuffActionModifyAttributeByWaveIndex:  BuffAction 
{
    public BuffActionModifyAttributeByWaveIndex(ByteBuf _buf)  : base(_buf) 
    {
        NumericType = (NumericType)_buf.ReadInt();
        BaseValue = _buf.ReadFloat();
        StackValue = _buf.ReadFloat();
        MaxChgValue = _buf.ReadFloat();
        PostInit();
    }

    public static BuffActionModifyAttributeByWaveIndex DeserializeBuffActionModifyAttributeByWaveIndex(ByteBuf _buf)
    {
        return new BuffActionModifyAttributeByWaveIndex(_buf);
    }

    /// <summary>
    /// 属性
    /// </summary>
    public NumericType NumericType { get; private set; }
    /// <summary>
    /// 初始附加
    /// </summary>
    public float BaseValue { get; private set; }
    /// <summary>
    /// 按照层数附加
    /// </summary>
    public float StackValue { get; private set; }
    /// <summary>
    /// 最大允许修改值(-1表示不限制)
    /// </summary>
    public float MaxChgValue { get; private set; }

    public const int __ID__ = -1506701879;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "BaseValue:" + BaseValue + ","
        + "StackValue:" + StackValue + ","
        + "MaxChgValue:" + MaxChgValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}