//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// Buff Tag标志
    /// </summary>
    public enum BuffTagType
    {
        BuffTagType1 = 1,
        BuffTagType2 = 2,
        BuffTagType3 = 3,
        BuffTagType4 = 4,
        /// <summary>
        /// 弱霸体
        /// </summary>
        SoftBati = 5,
        /// <summary>
        /// 强霸体
        /// </summary>
        StrongBati = 6,
        /// <summary>
        /// 虚弱(和霸体共存期间相当于无霸体)
        /// </summary>
        Weak = 7,
        /// <summary>
        /// 完全霸体（霸体表示 不受击退，击飞，禁锢等控制）
        /// </summary>
        FullBati = 8,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 9,
        /// <summary>
        /// 破弱霸体
        /// </summary>
        BreakSoftBati = 10,
        /// <summary>
        /// 破强霸体
        /// </summary>
        BreakStrongBati = 11,
        /// <summary>
        /// 移动输入(逻辑的移动？)
        /// </summary>
        NoMoveInput = 12,
        /// <summary>
        /// 技能输入
        /// </summary>
        NoSkillCastInput = 13,
        /// <summary>
        /// 修改面向输入(逻辑的修改面向？)
        /// </summary>
        NoFaceChgInput = 14,
        /// <summary>
        /// 不可被其他人看见
        /// </summary>
        Invisible = 15,
    }

} 
