//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 判断BuffId
/// </summary>
public sealed partial class BuffIdCondition:  Condition 
{
    public BuffIdCondition(ByteBuf _buf)  : base(_buf) 
    {
        BuffId = _buf.ReadString();
        PostInit();
    }

    public static BuffIdCondition DeserializeBuffIdCondition(ByteBuf _buf)
    {
        return new BuffIdCondition(_buf);
    }

    /// <summary>
    /// buffId
    /// </summary>
    public string BuffId { get; private set; }
    public BuffCfg BuffId_Ref { get; private set; }

    public const int __ID__ = -1544700979;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        this.BuffId_Ref = (_tables["BuffCfgCategory"] as BuffCfgCategory).GetOrDefault(BuffId);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "BuffId:" + BuffId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}