//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 通过阵营人数修改属性(teamPlayerCount表示实际波数)(float chgValue = buffActionModifyAttribute.BaseValueTeamPlayerCount*teamPlayerCount + buffActionModifyAttribute.StackValueTeamPlayerCount * stackCount*teamPlayerCount)
/// </summary>
public sealed partial class BuffActionModifyAttributeByTeamPlayerCount:  BuffAction 
{
    public BuffActionModifyAttributeByTeamPlayerCount(ByteBuf _buf)  : base(_buf) 
    {
        NumericType = (NumericType)_buf.ReadInt();
        BaseValueTeamPlayerCount = _buf.ReadFloat();
        StackValueTeamPlayerCount = _buf.ReadFloat();
        MaxChgValue = _buf.ReadFloat();
        PostInit();
    }

    public static BuffActionModifyAttributeByTeamPlayerCount DeserializeBuffActionModifyAttributeByTeamPlayerCount(ByteBuf _buf)
    {
        return new BuffActionModifyAttributeByTeamPlayerCount(_buf);
    }

    /// <summary>
    /// 属性
    /// </summary>
    public NumericType NumericType { get; private set; }
    /// <summary>
    /// 初始附加(通过阵营人数修改属性)
    /// </summary>
    public float BaseValueTeamPlayerCount { get; private set; }
    /// <summary>
    /// 按照层数附加(通过阵营人数修改属性)
    /// </summary>
    public float StackValueTeamPlayerCount { get; private set; }
    /// <summary>
    /// 最大允许修改值(-1表示不限制)
    /// </summary>
    public float MaxChgValue { get; private set; }

    public const int __ID__ = 1599702145;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "BaseValueTeamPlayerCount:" + BaseValueTeamPlayerCount + ","
        + "StackValueTeamPlayerCount:" + StackValueTeamPlayerCount + ","
        + "MaxChgValue:" + MaxChgValue + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}