//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 使用当前剩余时长进行修改(leftTime*leftTimeScale+stackCountScale*orgDuration*(stackCount-1))
/// </summary>
public sealed partial class BuffDurationChgCur:  BuffDurationChgType 
{
    public BuffDurationChgCur(ByteBuf _buf)  : base(_buf) 
    {
        LeftTimeScale = _buf.ReadFloat();
        StackCountScale = _buf.ReadFloat();
        PostInit();
    }

    public static BuffDurationChgCur DeserializeBuffDurationChgCur(ByteBuf _buf)
    {
        return new BuffDurationChgCur(_buf);
    }

    /// <summary>
    /// 剩余时长的缩放
    /// </summary>
    public float LeftTimeScale { get; private set; }
    /// <summary>
    /// 层数的缩放
    /// </summary>
    public float StackCountScale { get; private set; }

    public const int __ID__ = -796969915;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "LeftTimeScale:" + LeftTimeScale + ","
        + "StackCountScale:" + StackCountScale + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}