//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// callActor生成位置
    /// </summary>
    public enum CallActorPositionType
    {
        /// <summary>
        /// 上级Unit自身
        /// </summary>
        ByParent = 0,
        /// <summary>
        /// 随机位置
        /// </summary>
        MapRandom = 1,
        /// <summary>
        /// 路线上随机取n个点，在其周围m米内随机一点
        /// </summary>
        PathLineRandom = 2,
        /// <summary>
        /// 大本营，出怪点的中心点
        /// </summary>
        Center = 3,
    }

} 
