//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// callActor阵营类型
    /// </summary>
    public enum CallActorTeamFlagType
    {
        /// <summary>
        /// 上级UnitTeam
        /// </summary>
        ByParentTeam = 0,
        /// <summary>
        /// 大本营
        /// </summary>
        TeamGlobal = 1,
        /// <summary>
        /// 玩家
        /// </summary>
        TeamPlayer = 2,
        /// <summary>
        /// 玩家技能
        /// </summary>
        TeamPlayerSkill = 3,
        /// <summary>
        /// 刷怪点刷出来的怪
        /// </summary>
        TeamMonster = 4,
        /// <summary>
        /// 中立野怪
        /// </summary>
        TeamWildMonster = 5,
    }

} 
