//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 判断是否monster
/// </summary>
public sealed partial class ChkIsMonsterCondition:  UnitConditionBase 
{
    public ChkIsMonsterCondition(ByteBuf _buf)  : base(_buf) 
    {
        MonsterType = (MonsterType)_buf.ReadInt();
        PostInit();
    }

    public static ChkIsMonsterCondition DeserializeChkIsMonsterCondition(ByteBuf _buf)
    {
        return new ChkIsMonsterCondition(_buf);
    }

    /// <summary>
    /// monsterType
    /// </summary>
    public MonsterType MonsterType { get; private set; }

    public const int __ID__ = -291821871;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ConditionCompare:" + ConditionCompare + ","
        + "MonsterType:" + MonsterType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}