//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 掉落规则类型
    /// </summary>
    public enum DropRuleType
    {
        /// <summary>
        /// 按几率独立掉落
        /// </summary>
        DropAll = 1,
        /// <summary>
        /// 按权重单一掉落
        /// </summary>
        DropOne = 2,
    }

} 
