//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 掉落道具属性
/// </summary>
public abstract partial class DropItemBase: Bright.Config.BeanBase
{
    public DropItemBase(ByteBuf _buf) 
    {
        DropNum = _buf.ReadInt();
        DropRatio = _buf.ReadInt();
        PostInit();
    }

    public static DropItemBase DeserializeDropItemBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case DropItemOne.__ID__: return new DropItemOne(_buf);
            case DropRuleOne.__ID__: return new DropRuleOne(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 掉落数量
    /// </summary>
    public int DropNum { get; private set; }
    /// <summary>
    /// 掉落概率万分比
    /// </summary>
    public int DropRatio { get; private set; }


    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DropNum:" + DropNum + ","
        + "DropRatio:" + DropRatio + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}