//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 特效表现类型
    /// </summary>
    public enum EffectShowType
    {
        /// <summary>
        /// 点特效
        /// </summary>
        Point = 1,
        /// <summary>
        /// 点特效(闪电拖尾)
        /// </summary>
        PointLightningTrail = 2,
        /// <summary>
        /// 点特效(仅客户端表现移动到Unit)
        /// </summary>
        PointClienShowMove = 3,
        /// <summary>
        /// 线特效(发起者-接收者1;发起者-接收者2)
        /// </summary>
        Send2Receives = 4,
        /// <summary>
        /// 线特效(发起者-接收者1-接收者2...)
        /// </summary>
        Send2Receive2Receive = 5,
    }

} 
