//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 物品子类型
    /// </summary>
    public enum ItemSubType
    {
        /// <summary>
        /// 塔
        /// </summary>
        Tower = 0,
        /// <summary>
        /// 召唤怪物
        /// </summary>
        CallMonster = 1,
        /// <summary>
        /// 怪物1
        /// </summary>
        Monster1 = 0,
    }

} 
