//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class LocalizeConfig_CN:  ALocalizeConfig 
{
    public LocalizeConfig_CN(ByteBuf _buf)  : base(_buf) 
    {
        TextCn = _buf.ReadString();
        PostInit();
    }

    public static LocalizeConfig_CN DeserializeLocalizeConfig_CN(ByteBuf _buf)
    {
        return new LocalizeConfig_CN(_buf);
    }

    public string TextCn { get; private set; }

    public const int __ID__ = 2049582687;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "TextCn:" + TextCn + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}