//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public abstract partial class MoveTweenType: Bright.Config.BeanBase
{
    public MoveTweenType(ByteBuf _buf) 
    {
        Speed = _buf.ReadFloat();
        AcceleratedSpeed = _buf.ReadFloat();
        PostInit();
    }

    public static MoveTweenType DeserializeMoveTweenType(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case StraightMoveTweenType.__ID__: return new StraightMoveTweenType(_buf);
            case TrackingMoveTweenType.__ID__: return new TrackingMoveTweenType(_buf);
            case AroundMoveTweenType.__ID__: return new AroundMoveTweenType(_buf);
            case ParabolaMoveTweenType.__ID__: return new ParabolaMoveTweenType(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 速度
    /// </summary>
    public float Speed { get; private set; }
    /// <summary>
    /// 加速度
    /// </summary>
    public float AcceleratedSpeed { get; private set; }


    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Speed:" + Speed + ","
        + "AcceleratedSpeed:" + AcceleratedSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}