//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.AbilityConfig
{ 
    /// <summary>
    /// 目标选择对象类型
    /// </summary>
    public enum SelectObjectType
    {
        /// <summary>
        /// 不限制
        /// </summary>
        All = 1,
        /// <summary>
        /// 自己所有对象
        /// </summary>
        Self = 2,
        /// <summary>
        /// 自己玩家
        /// </summary>
        SelfPlayer = 3,
        /// <summary>
        /// 友军
        /// </summary>
        Friends = 4,
        /// <summary>
        /// 友军玩家
        /// </summary>
        FriendPlayers = 5,
        /// <summary>
        /// 友军非玩家
        /// </summary>
        FriendButNotPlayers = 6,
        /// <summary>
        /// 敌军
        /// </summary>
        Hostiles = 7,
        /// <summary>
        /// 敌军玩家
        /// </summary>
        HostilePlayers = 8,
        /// <summary>
        /// 敌军非玩家
        /// </summary>
        HostileButNotPlayers = 9,
        /// <summary>
        /// 所有玩家
        /// </summary>
        AllPlayers = 10,
        /// <summary>
        /// 所有非玩家
        /// </summary>
        AllButNotPlayers = 11,
    }

} 
