//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public abstract partial class TeamModeBase: Bright.Config.BeanBase
{
    public TeamModeBase(ByteBuf _buf) 
    {
        PostInit();
    }

    public static TeamModeBase DeserializeTeamModeBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case AllPlayersOneGroup.__ID__: return new AllPlayersOneGroup(_buf);
            case PlayerAlone.__ID__: return new PlayerAlone(_buf);
            case PlayerTeam.__ID__: return new PlayerTeam(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}