//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET.AbilityConfig
{
   
/// <summary>
/// 玩法_塔防_闯关模式配置
/// </summary>
[Config]
public partial class TowerDefense_ChallengeLevelCfgCategory: ConfigSingleton<TowerDefense_ChallengeLevelCfgCategory>
{
    private readonly List<ChallengeLevelCfg> _dataList;

    private Dictionary<(int, PVELevelDifficulty), ChallengeLevelCfg> _dataMapUnion;

    public TowerDefense_ChallengeLevelCfgCategory(ByteBuf _buf)
    {
        _dataList = new List<ChallengeLevelCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ChallengeLevelCfg _v;
            _v = ChallengeLevelCfg.DeserializeChallengeLevelCfg(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, PVELevelDifficulty), ChallengeLevelCfg>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Index, _v.PveLevelDifficulty), _v);
        }
        PostInit();
    }

    public List<ChallengeLevelCfg> DataList => _dataList;

    public ChallengeLevelCfg Get(int index, PVELevelDifficulty pveLevelDifficulty) => _dataMapUnion.TryGetValue((index, pveLevelDifficulty), out ChallengeLevelCfg __v) ? __v : null;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(ChallengeLevelCfg).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}