//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

public sealed partial class TowerDefense_BuyTowerRefreshRuleCfg: Bright.Config.BeanBase
{
    public TowerDefense_BuyTowerRefreshRuleCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TowerWeight = new System.Collections.Generic.Dictionary<string, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); int _v0;  _v0 = _buf.ReadInt();     TowerWeight.Add(_k0, _v0);}}
        PostInit();
    }

    public static TowerDefense_BuyTowerRefreshRuleCfg DeserializeTowerDefense_BuyTowerRefreshRuleCfg(ByteBuf _buf)
    {
        return new TowerDefense_BuyTowerRefreshRuleCfg(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// towerId
    /// </summary>
    public System.Collections.Generic.Dictionary<string, int> TowerWeight { get; private set; }

    public const int __ID__ = -621375048;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "TowerWeight:" + Bright.Common.StringUtil.CollectionToString(TowerWeight) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}