//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// towerCfgId对应具体
/// </summary>
public abstract partial class TowerToUnitBase: Bright.Config.BeanBase
{
    public TowerToUnitBase(ByteBuf _buf) 
    {
        PostInit();
    }

    public static TowerToUnitBase DeserializeTowerToUnitBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case TowerToUnitCfgId.__ID__: return new TowerToUnitCfgId(_buf);
            case TowerToMonsterCfgId.__ID__: return new TowerToMonsterCfgId(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}