//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 战斗中金币获得规则
/// </summary>
public sealed partial class TowerDefenseIncreaseGold: Bright.Config.BeanBase
{
    public TowerDefenseIncreaseGold(ByteBuf _buf) 
    {
        PlayerInitGold = _buf.ReadInt();
        InitGoldWhenWave = _buf.ReadInt();
        IncreaseGoldWhenWave = _buf.ReadFloat();
        IncreasePercentGoldWhenWave = _buf.ReadFloat();
        Interval = _buf.ReadInt();
        InitGoldWhenInterval = _buf.ReadInt();
        IncreaseGoldWhenInterval = _buf.ReadFloat();
        IncreasePercentGoldWhenInterval = _buf.ReadFloat();
        PostInit();
    }

    public static TowerDefenseIncreaseGold DeserializeTowerDefenseIncreaseGold(ByteBuf _buf)
    {
        return new TowerDefenseIncreaseGold(_buf);
    }

    /// <summary>
    /// 阵营初始个人金币
    /// </summary>
    public int PlayerInitGold { get; private set; }
    /// <summary>
    /// 波次奖励
    /// </summary>
    public int InitGoldWhenWave { get; private set; }
    /// <summary>
    /// 波次奖励固定增长
    /// </summary>
    public float IncreaseGoldWhenWave { get; private set; }
    /// <summary>
    /// 波次奖励固定百分比增长(0-1)
    /// </summary>
    public float IncreasePercentGoldWhenWave { get; private set; }
    /// <summary>
    /// 定时奖励间隔(秒)
    /// </summary>
    public int Interval { get; private set; }
    /// <summary>
    /// 定时奖励
    /// </summary>
    public int InitGoldWhenInterval { get; private set; }
    /// <summary>
    /// 定时奖励固定增长
    /// </summary>
    public float IncreaseGoldWhenInterval { get; private set; }
    /// <summary>
    /// 定时奖励固定百分比增长(0-1)
    /// </summary>
    public float IncreasePercentGoldWhenInterval { get; private set; }

    public const int __ID__ = 2081239673;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PlayerInitGold:" + PlayerInitGold + ","
        + "InitGoldWhenWave:" + InitGoldWhenWave + ","
        + "IncreaseGoldWhenWave:" + IncreaseGoldWhenWave + ","
        + "IncreasePercentGoldWhenWave:" + IncreasePercentGoldWhenWave + ","
        + "Interval:" + Interval + ","
        + "InitGoldWhenInterval:" + InitGoldWhenInterval + ","
        + "IncreaseGoldWhenInterval:" + IncreaseGoldWhenInterval + ","
        + "IncreasePercentGoldWhenInterval:" + IncreasePercentGoldWhenInterval + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}