//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 出售塔
/// </summary>
public sealed partial class TriggerImmediatelyScaleTower:  TriggerImmediatelyBase 
{
    public TriggerImmediatelyScaleTower(ByteBuf _buf)  : base(_buf) 
    {
        TowerType = (TowerType)_buf.ReadInt();
        TowerCfgId = _buf.ReadString();
        PostInit();
    }

    public static TriggerImmediatelyScaleTower DeserializeTriggerImmediatelyScaleTower(ByteBuf _buf)
    {
        return new TriggerImmediatelyScaleTower(_buf);
    }

    public TowerType TowerType { get; private set; }
    public string TowerCfgId { get; private set; }
    public TowerDefense_TowerCfg TowerCfgId_Ref { get; private set; }

    public const int __ID__ = 1913999557;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        this.TowerCfgId_Ref = (_tables["TowerDefense_TowerCfgCategory"] as TowerDefense_TowerCfgCategory).GetOrDefault(TowerCfgId);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "TriggerType:" + TriggerType + ","
        + "TowerType:" + TowerType + ","
        + "TowerCfgId:" + TowerCfgId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}