//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET.AbilityConfig
{

/// <summary>
/// 条件判断触发
/// </summary>
public abstract partial class TriggerChkConditionBase:  ChkTriggerBase 
{
    public TriggerChkConditionBase(ByteBuf _buf)  : base(_buf) 
    {
        NeedCount = _buf.ReadInt();
        PostInit();
    }

    public static TriggerChkConditionBase DeserializeTriggerChkConditionBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case TriggerChkConditionImmediately.__ID__: return new TriggerChkConditionImmediately(_buf);
            case TriggerChkConditionStatus.__ID__: return new TriggerChkConditionStatus(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 需要触发次数
    /// </summary>
    public int NeedCount { get; private set; }


    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NeedCount:" + NeedCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}